# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignRecognition_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        # 增加窗口尺寸
        MainWindow.resize(1200, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        # 设置渐变背景色
        MainWindow.setStyleSheet("""
            QMainWindow {
                background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, 
                                     stop:0 #f8f9fa, stop:1 #e9ecef);
            }
        """)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # 主标题背景面板 - 去掉底部边框线
        self.title_panel = QtWidgets.QFrame(self.centralwidget)
        self.title_panel.setGeometry(QtCore.QRect(0, 0, 1200, 120))
        self.title_panel.setStyleSheet("""
            QFrame {
                background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, 
                                   stop:0 #4cc9f0, stop:0.5 #4361ee, stop:1 #3a0ca3);
                border-radius: 0px;
            }
        """)
        self.title_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_panel.setObjectName("title_panel")
        
        # 标题 - 放大字体
        self.label_title = QtWidgets.QLabel(self.title_panel)
        self.label_title.setGeometry(QtCore.QRect(250, 30, 700, 70))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(30)  # 放大字体
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: white; background-color: transparent; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        
        # 创建一个内容面板，包含所有其他控件 - 调整大小
        self.content_panel = QtWidgets.QFrame(self.centralwidget)
        self.content_panel.setGeometry(QtCore.QRect(20, 140, 1160, 730))
        self.content_panel.setStyleSheet("""
            QFrame {
                background-color: white;
                border-radius: 10px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }
        """)
        self.content_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_panel.setObjectName("content_panel")
        
        # 显示区域 - 放大
        self.display_panel = QtWidgets.QFrame(self.content_panel)
        self.display_panel.setGeometry(QtCore.QRect(20, 20, 750, 680))
        self.display_panel.setStyleSheet("""
            QFrame {
                background-color: #f8f9fa;
                border-radius: 8px;
                border: 1px solid #dee2e6;
            }
        """)
        self.display_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.display_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.display_panel.setObjectName("display_panel")
        
        # 显示标签 - 放大
        self.label_display = QtWidgets.QLabel(self.display_panel)
        self.label_display.setGeometry(QtCore.QRect(10, 10, 730, 660))
        self.label_display.setStyleSheet("""
            QLabel {
                background-color: white;
                border-radius: 4px;
                border: 1px solid #dee2e6;
            }
        """)
        self.label_display.setAlignment(QtCore.Qt.AlignCenter)
        self.label_display.setObjectName("label_display")
        
        # 控制面板（右侧）- 调整位置和大小
        self.control_panel = QtWidgets.QFrame(self.content_panel)
        self.control_panel.setGeometry(QtCore.QRect(790, 20, 350, 680))
        self.control_panel.setStyleSheet("""
            QFrame {
                background-color: #f8f9fa;
                border-radius: 8px;
                border: 1px solid #dee2e6;
            }
        """)
        self.control_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_panel.setObjectName("control_panel")
        
        # 操作区域标题 - 调整大小
        self.label_operation_title = QtWidgets.QLabel(self.control_panel)
        self.label_operation_title.setGeometry(QtCore.QRect(10, 10, 330, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)  # 放大字体
        font.setBold(True)
        self.label_operation_title.setFont(font)
        self.label_operation_title.setStyleSheet("""
            color: white; 
            background-color: #4361ee; 
            border: none;
            border-radius: 4px;
            padding-left: 10px;
        """)
        self.label_operation_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_operation_title.setObjectName("label_operation_title")
        
        # 按钮组样式 - 放大
        self.buttons_frame = QtWidgets.QFrame(self.control_panel)
        self.buttons_frame.setGeometry(QtCore.QRect(10, 60, 330, 180))
        self.buttons_frame.setStyleSheet("""
            QFrame {
                background-color: white;
                border-radius: 6px;
                border: 1px solid #e9ecef;
            }
        """)
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        
        # 按钮样式（统一样式）- 调整大小和字体
        button_style = """
            QToolButton {
                background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, 
                                   stop:0 #4cc9f0, stop:1 #4361ee);
                color: white;
                border-radius: 20px;
                font-family: '微软雅黑';
                font-size: 14px;
                font-weight: bold;
            }
            QToolButton:hover {
                background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, 
                                   stop:0 #4361ee, stop:1 #3a0ca3);
            }
            QToolButton:pressed {
                background-color: #3f37c9;
            }
        """
        
        # 图片选择按钮 - 调整位置和大小
        self.toolButton_pic = QtWidgets.QToolButton(self.buttons_frame)
        self.toolButton_pic.setGeometry(QtCore.QRect(15, 20, 120, 40))
        self.toolButton_pic.setStyleSheet(button_style)
        self.toolButton_pic.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_pic.setText("图片")
        self.toolButton_pic.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_pic.setObjectName("toolButton_pic")
        
        # 选择图片文件文本框 - 美化样式
        self.textEdit_pic = QtWidgets.QTextEdit(self.buttons_frame)
        self.textEdit_pic.setGeometry(QtCore.QRect(145, 20, 170, 40))
        self.textEdit_pic.setStyleSheet("""
            QTextEdit {
                background-color: #f8f9fa;
                border: 1px solid #ced4da;
                border-radius: 4px;
                padding: 5px 8px;
                color: #495057;
                font-family: '微软雅黑';
                font-size: 12px;
                line-height: 1.2;
            }
            QTextEdit:focus {
                border-color: #4361ee;
                outline: 0;
                box-shadow: 0 0 0 3px rgba(67, 97, 238, 0.25);
            }
        """)
        self.textEdit_pic.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_pic.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_pic.setReadOnly(True)
        self.textEdit_pic.setObjectName("textEdit_pic")
        
        # 摄像头按钮 - 调整位置和大小
        self.toolButton_camera = QtWidgets.QToolButton(self.buttons_frame)
        self.toolButton_camera.setGeometry(QtCore.QRect(15, 70, 120, 40))
        self.toolButton_camera.setStyleSheet(button_style)
        self.toolButton_camera.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_camera.setText("摄像头")
        self.toolButton_camera.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_camera.setObjectName("toolButton_camera")
        
        # 摄像头文本框 - 美化样式
        self.textEdit_camera = QtWidgets.QTextEdit(self.buttons_frame)
        self.textEdit_camera.setGeometry(QtCore.QRect(145, 70, 170, 40))
        self.textEdit_camera.setStyleSheet("""
            QTextEdit {
                background-color: #f8f9fa;
                border: 1px solid #ced4da;
                border-radius: 4px;
                padding: 5px 8px;
                color: #495057;
                font-family: '微软雅黑';
                font-size: 12px;
                line-height: 1.2;
            }
            QTextEdit:focus {
                border-color: #4361ee;
                outline: 0;
                box-shadow: 0 0 0 3px rgba(67, 97, 238, 0.25);
            }
        """)
        self.textEdit_camera.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_camera.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_camera.setReadOnly(True)
        self.textEdit_camera.setObjectName("textEdit_camera")
        
        # 视频按钮 - 调整位置和大小
        self.toolButton_video = QtWidgets.QToolButton(self.buttons_frame)
        self.toolButton_video.setGeometry(QtCore.QRect(15, 120, 120, 40))
        self.toolButton_video.setStyleSheet(button_style)
        self.toolButton_video.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_video.setText("视频")
        self.toolButton_video.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_video.setObjectName("toolButton_video")
        
        # 视频文本框 - 美化样式
        self.textEdit_video = QtWidgets.QTextEdit(self.buttons_frame)
        self.textEdit_video.setGeometry(QtCore.QRect(145, 120, 170, 40))
        self.textEdit_video.setStyleSheet("""
            QTextEdit {
                background-color: #f8f9fa;
                border: 1px solid #ced4da;
                border-radius: 4px;
                padding: 5px 8px;
                color: #495057;
                font-family: '微软雅黑';
                font-size: 12px;
                line-height: 1.2;
            }
            QTextEdit:focus {
                border-color: #4361ee;
                outline: 0;
                box-shadow: 0 0 0 3px rgba(67, 97, 238, 0.25);
            }
        """)
        self.textEdit_video.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_video.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_video.setReadOnly(True)
        self.textEdit_video.setObjectName("textEdit_video")
        
        # 状态信息面板 - 调整位置和大小
        self.status_frame = QtWidgets.QFrame(self.control_panel)
        self.status_frame.setGeometry(QtCore.QRect(10, 250, 330, 100))
        self.status_frame.setStyleSheet("""
            QFrame {
                background-color: white;
                border-radius: 6px;
                border: 1px solid #e9ecef;
            }
        """)
        self.status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_frame.setObjectName("status_frame")
        
        # 状态信息标题
        self.label_status_title = QtWidgets.QLabel(self.status_frame)
        self.label_status_title.setGeometry(QtCore.QRect(10, 0, 310, 20))
        self.label_status_title.setStyleSheet("""
            font-family: '微软雅黑';
            font-size: 12px;
            font-weight: bold;
            color: #4361ee;
            background-color: transparent;
            border: none;
        """)
        self.label_status_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_title.setObjectName("label_status_title")
        
        # 信息显示区域样式 - 放大字体
        info_label_style = """
            QLabel {
                font-family: '微软雅黑';
                font-size: 14px;
                color: #343a40;
                background-color: transparent;
                border: none;
            }
        """
        
        info_value_style = """
            QLabel {
                font-family: '微软雅黑';
                font-size: 14px;
                font-weight: bold;
                color: #4361ee;
                background-color: transparent;
                border: none;
            }
        """
        
        # FPS显示 - 调整位置
        self.label_fps_title = QtWidgets.QLabel(self.status_frame)
        self.label_fps_title.setGeometry(QtCore.QRect(20, 20, 60, 30))
        self.label_fps_title.setStyleSheet(info_label_style)
        self.label_fps_title.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_fps_title.setObjectName("label_fps_title")
        
        self.label_time_result = QtWidgets.QLabel(self.status_frame)
        self.label_time_result.setGeometry(QtCore.QRect(80, 20, 60, 30))
        self.label_time_result.setStyleSheet(info_value_style)
        self.label_time_result.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time_result.setObjectName("label_time_result")
        
        # 手势数目 - 调整位置
        self.label_gesture_num = QtWidgets.QLabel(self.status_frame)
        self.label_gesture_num.setGeometry(QtCore.QRect(160, 20, 100, 30))
        self.label_gesture_num.setStyleSheet(info_label_style)
        self.label_gesture_num.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_gesture_num.setObjectName("label_gesture_num")
        
        self.label_numer_result = QtWidgets.QLabel(self.status_frame)
        self.label_numer_result.setGeometry(QtCore.QRect(260, 20, 50, 30))
        self.label_numer_result.setStyleSheet(info_value_style)
        self.label_numer_result.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_numer_result.setObjectName("label_numer_result")
        
        # 手势选择下拉框 - 调整大小
        self.comboBox_select = QtWidgets.QComboBox(self.status_frame)
        self.comboBox_select.setGeometry(QtCore.QRect(20, 55, 290, 35))
        self.comboBox_select.setStyleSheet("""
            QComboBox {
                background-color: #f8f9fa;
                border: 1px solid #ced4da;
                border-radius: 4px;
                padding: 5px;
                color: #495057;
                font-family: '微软雅黑';
                font-size: 13px;
            }
            QComboBox::drop-down {
                border: none;
                width: 20px;
            }
            QComboBox QAbstractItemView {
                background-color: white;
                selection-background-color: #4361ee;
                selection-color: white;
                border: 1px solid #ced4da;
            }
        """)
        self.comboBox_select.setObjectName("comboBox_select")
        self.comboBox_select.addItem("")
        
        # 结果区域标题 - 调整位置和大小
        self.label_result_title = QtWidgets.QLabel(self.control_panel)
        self.label_result_title.setGeometry(QtCore.QRect(10, 360, 330, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        self.label_result_title.setFont(font)
        self.label_result_title.setStyleSheet("""
            color: white; 
            background-color: #4361ee; 
            border: none;
            border-radius: 4px;
            padding-left: 10px;
        """)
        self.label_result_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result_title.setObjectName("label_result_title")
        self.label_result_title.setVisible(True)
        
        # 结果1面板 - 调整位置和大小
        self.result_panel = QtWidgets.QFrame(self.control_panel)
        self.result_panel.setGeometry(QtCore.QRect(10, 410, 330, 120))
        self.result_panel.setStyleSheet("""
            QFrame {
                background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, 
                           stop:0 #f8f9fa, stop:1 #e2e8f0);
                border-radius: 6px;
                border: 1px solid #e9ecef;
            }
        """)
        self.result_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.result_panel.setObjectName("result_panel")
        
        # 结果1标题 - 调整位置和大小
        self.result_title = QtWidgets.QLabel(self.result_panel)
        self.result_title.setGeometry(QtCore.QRect(10, 10, 310, 30))
        self.result_title.setStyleSheet("""
            background-color: #4cc9f0;
            color: white;
            font-family: '微软雅黑';
            font-size: 14px;
            font-weight: bold;
            border-radius: 3px;
            padding-left: 10px;
        """)
        self.result_title.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.result_title.setObjectName("result_title")
        
        # 结果1数据 - 调整位置和大小
        self.label_result = QtWidgets.QLabel(self.result_panel)
        self.label_result.setGeometry(QtCore.QRect(15, 50, 60, 35))
        self.label_result.setStyleSheet(info_label_style)
        self.label_result.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_result.setObjectName("label_result")
        
        self.label_class_result = QtWidgets.QLabel(self.result_panel)
        self.label_class_result.setGeometry(QtCore.QRect(75, 50, 150, 35))
        self.label_class_result.setStyleSheet("""
            font-family: '微软雅黑';
            font-size: 14px;
            font-weight: bold;
            color: #f72585;
            background-color: transparent;
            border: none;
        """)
        self.label_class_result.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_class_result.setObjectName("label_class_result")
        
        # 手指数 - 调整位置和大小
        self.label_finger_num = QtWidgets.QLabel(self.result_panel)
        self.label_finger_num.setGeometry(QtCore.QRect(15, 85, 80, 35))
        self.label_finger_num.setStyleSheet(info_label_style)
        self.label_finger_num.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_finger_num.setObjectName("label_finger_num")
        
        self.label_numer_score = QtWidgets.QLabel(self.result_panel)
        self.label_numer_score.setGeometry(QtCore.QRect(95, 85, 50, 35))
        self.label_numer_score.setStyleSheet("""
            font-family: '微软雅黑';
            font-size: 14px;
            font-weight: bold;
            color: #f72585;
            background-color: transparent;
            border: none;
        """)
        self.label_numer_score.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_numer_score.setObjectName("label_numer_score")
        
        # 添加置信度滑块到手势1结果面板
        self.label_conf_threshold_1 = QtWidgets.QLabel(self.result_panel)
        self.label_conf_threshold_1.setGeometry(QtCore.QRect(15, 85, 80, 35))
        self.label_conf_threshold_1.setStyleSheet(info_label_style)
        self.label_conf_threshold_1.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_conf_threshold_1.setObjectName("label_conf_threshold_1")
        self.label_conf_threshold_1.setText("置信度:")
        
        self.slider_conf_1 = QtWidgets.QSlider(self.result_panel)
        self.slider_conf_1.setGeometry(QtCore.QRect(95, 90, 85, 25))
        self.slider_conf_1.setMinimum(1)
        self.slider_conf_1.setMaximum(10)
        self.slider_conf_1.setValue(5)
        self.slider_conf_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_conf_1.setObjectName("slider_conf_1")
        
        self.label_conf_value_1 = QtWidgets.QLabel(self.result_panel)
        self.label_conf_value_1.setGeometry(QtCore.QRect(185, 85, 30, 35))
        self.label_conf_value_1.setStyleSheet(info_value_style)
        self.label_conf_value_1.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_conf_value_1.setObjectName("label_conf_value_1")
        self.label_conf_value_1.setText("0.5")
        
        # 添加IOU滑块到手势1结果面板
        self.label_iou_threshold_1 = QtWidgets.QLabel(self.result_panel)
        self.label_iou_threshold_1.setGeometry(QtCore.QRect(210, 85, 40, 35))
        self.label_iou_threshold_1.setStyleSheet(info_label_style)
        self.label_iou_threshold_1.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_iou_threshold_1.setObjectName("label_iou_threshold_1")
        self.label_iou_threshold_1.setText("IOU:")
        
        self.slider_iou_1 = QtWidgets.QSlider(self.result_panel)
        self.slider_iou_1.setGeometry(QtCore.QRect(250, 90, 45, 25))
        self.slider_iou_1.setMinimum(1)
        self.slider_iou_1.setMaximum(10)
        self.slider_iou_1.setValue(5)
        self.slider_iou_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_iou_1.setObjectName("slider_iou_1")
        
        self.label_iou_value_1 = QtWidgets.QLabel(self.result_panel)
        self.label_iou_value_1.setGeometry(QtCore.QRect(300, 85, 30, 35))
        self.label_iou_value_1.setStyleSheet(info_value_style)
        self.label_iou_value_1.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_iou_value_1.setObjectName("label_iou_value_1")
        self.label_iou_value_1.setText("0.5")
        
        # 结果2面板 - 调整位置和大小
        self.result_panel_2 = QtWidgets.QFrame(self.control_panel)
        self.result_panel_2.setGeometry(QtCore.QRect(10, 540, 330, 120))
        self.result_panel_2.setStyleSheet("""
            QFrame {
                background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, 
                           stop:0 #f8f9fa, stop:1 #e2e8f0);
                border-radius: 6px;
                border: 1px solid #e9ecef;
            }
        """)
        self.result_panel_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_panel_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.result_panel_2.setObjectName("result_panel_2")
        
        # 结果2标题 - 调整位置和大小
        self.result2_title = QtWidgets.QLabel(self.result_panel_2)
        self.result2_title.setGeometry(QtCore.QRect(10, 10, 310, 30))
        self.result2_title.setStyleSheet("""
            background-color: #4361ee;
            color: white;
            font-family: '微软雅黑';
            font-size: 14px;
            font-weight: bold;
            border-radius: 3px;
            padding-left: 10px;
        """)
        self.result2_title.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.result2_title.setObjectName("result2_title")
        
        # 结果2数据 - 调整位置和大小
        self.label_result2 = QtWidgets.QLabel(self.result_panel_2)
        self.label_result2.setGeometry(QtCore.QRect(15, 50, 60, 35))
        self.label_result2.setStyleSheet(info_label_style)
        self.label_result2.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_result2.setObjectName("label_result2")
        
        # 原来隐藏的label_class_result_2显示出来 - 调整位置和大小
        self.label_class_result_2 = QtWidgets.QLabel(self.result_panel_2)
        self.label_class_result_2.setGeometry(QtCore.QRect(75, 50, 150, 35))
        self.label_class_result_2.setStyleSheet("""
            font-family: '微软雅黑';
            font-size: 14px;
            font-weight: bold;
            color: #4361ee;
            background-color: transparent;
            border: none;
        """)
        self.label_class_result_2.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_class_result_2.setObjectName("label_class_result_2")
        
        # 第二个手指数 - 调整位置和大小
        self.label_finger_num_2 = QtWidgets.QLabel(self.result_panel_2)
        self.label_finger_num_2.setGeometry(QtCore.QRect(15, 85, 80, 35))
        self.label_finger_num_2.setStyleSheet(info_label_style)
        self.label_finger_num_2.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_finger_num_2.setObjectName("label_finger_num_2")
        
        self.label_numer_score_2 = QtWidgets.QLabel(self.result_panel_2)
        self.label_numer_score_2.setGeometry(QtCore.QRect(95, 85, 50, 35))
        self.label_numer_score_2.setStyleSheet("""
            font-family: '微软雅黑';
            font-size: 14px;
            font-weight: bold;
            color: #f72585;
            background-color: transparent;
            border: none;
        """)
        self.label_numer_score_2.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_numer_score_2.setObjectName("label_numer_score_2")
        
        # 添加置信度滑块到手势2结果面板
        self.label_conf_threshold_2 = QtWidgets.QLabel(self.result_panel_2)
        self.label_conf_threshold_2.setGeometry(QtCore.QRect(15, 85, 80, 35))
        self.label_conf_threshold_2.setStyleSheet(info_label_style)
        self.label_conf_threshold_2.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_conf_threshold_2.setObjectName("label_conf_threshold_2")
        self.label_conf_threshold_2.setText("置信度:")
        
        self.slider_conf_2 = QtWidgets.QSlider(self.result_panel_2)
        self.slider_conf_2.setGeometry(QtCore.QRect(95, 90, 85, 25))
        self.slider_conf_2.setMinimum(1)
        self.slider_conf_2.setMaximum(10)
        self.slider_conf_2.setValue(5)
        self.slider_conf_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_conf_2.setObjectName("slider_conf_2")
        
        self.label_conf_value_2 = QtWidgets.QLabel(self.result_panel_2)
        self.label_conf_value_2.setGeometry(QtCore.QRect(185, 85, 30, 35))
        self.label_conf_value_2.setStyleSheet(info_value_style)
        self.label_conf_value_2.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_conf_value_2.setObjectName("label_conf_value_2")
        self.label_conf_value_2.setText("0.5")
        
        # 添加IOU滑块到手势2结果面板
        self.label_iou_threshold_2 = QtWidgets.QLabel(self.result_panel_2)
        self.label_iou_threshold_2.setGeometry(QtCore.QRect(210, 85, 40, 35))
        self.label_iou_threshold_2.setStyleSheet(info_label_style)
        self.label_iou_threshold_2.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_iou_threshold_2.setObjectName("label_iou_threshold_2")
        self.label_iou_threshold_2.setText("IOU:")
        
        self.slider_iou_2 = QtWidgets.QSlider(self.result_panel_2)
        self.slider_iou_2.setGeometry(QtCore.QRect(250, 90, 45, 25))
        self.slider_iou_2.setMinimum(1)
        self.slider_iou_2.setMaximum(10)
        self.slider_iou_2.setValue(5)
        self.slider_iou_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_iou_2.setObjectName("slider_iou_2")
        
        self.label_iou_value_2 = QtWidgets.QLabel(self.result_panel_2)
        self.label_iou_value_2.setGeometry(QtCore.QRect(300, 85, 30, 35))
        self.label_iou_value_2.setStyleSheet(info_value_style)
        self.label_iou_value_2.setAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_iou_value_2.setObjectName("label_iou_value_2")
        self.label_iou_value_2.setText("0.5")
        
        # 保留兼容性 - 创建不可见的滑块和标签
        self.threshold_panel = QtWidgets.QFrame(self.centralwidget)
        self.threshold_panel.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.threshold_panel.setVisible(False)
        self.threshold_panel.setObjectName("threshold_panel")
        
        self.label_conf_threshold = QtWidgets.QLabel(self.threshold_panel)
        self.label_conf_threshold.setObjectName("label_conf_threshold")
        
        self.slider_conf = QtWidgets.QSlider(self.threshold_panel)
        self.slider_conf.setMinimum(1)
        self.slider_conf.setMaximum(10)
        self.slider_conf.setValue(5)
        self.slider_conf.setOrientation(QtCore.Qt.Horizontal)
        self.slider_conf.setObjectName("slider_conf")
        
        self.label_conf_value = QtWidgets.QLabel(self.threshold_panel)
        self.label_conf_value.setObjectName("label_conf_value")
        
        self.label_iou_threshold = QtWidgets.QLabel(self.threshold_panel)
        self.label_iou_threshold.setObjectName("label_iou_threshold")
        
        self.slider_iou = QtWidgets.QSlider(self.threshold_panel)
        self.slider_iou.setMinimum(1)
        self.slider_iou.setMaximum(10)
        self.slider_iou.setValue(5)
        self.slider_iou.setOrientation(QtCore.Qt.Horizontal)
        self.slider_iou.setObjectName("slider_iou")
        
        self.label_iou_value = QtWidgets.QLabel(self.threshold_panel)
        self.label_iou_value.setObjectName("label_iou_value")
        
        # 状态栏
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("""
            QStatusBar {
                background-color: #f8f9fa;
                color: #6c757d;
                font-family: '微软雅黑';
                font-size: 12px;
            }
        """)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        # 隐藏的坐标字段（保持兼容性）
        self.label_xmin_result = QtWidgets.QLabel(self.centralwidget)
        self.label_xmin_result.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_xmin_result.setVisible(False)
        self.label_xmin_result.setText("0")
        self.label_xmin_result.setObjectName("label_xmin_result")
        
        self.label_ymin_result = QtWidgets.QLabel(self.centralwidget)
        self.label_ymin_result.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_ymin_result.setVisible(False)
        self.label_ymin_result.setText("0")
        self.label_ymin_result.setObjectName("label_ymin_result")
        
        self.label_xmax_result = QtWidgets.QLabel(self.centralwidget)
        self.label_xmax_result.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_xmax_result.setVisible(False)
        self.label_xmax_result.setText("0")
        self.label_xmax_result.setObjectName("label_xmax_result")
        
        self.label_ymax_result = QtWidgets.QLabel(self.centralwidget)
        self.label_ymax_result.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_ymax_result.setVisible(False)
        self.label_ymax_result.setText("0")
        self.label_ymax_result.setObjectName("label_ymax_result")
        
        # 坐标字段标题
        self.label_coordinates_title = QtWidgets.QLabel(self.centralwidget)
        self.label_coordinates_title.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_coordinates_title.setVisible(False)
        self.label_coordinates_title.setText("坐标信息")
        self.label_coordinates_title.setObjectName("label_coordinates_title")
        
        self.label_xmin_title = QtWidgets.QLabel(self.centralwidget)
        self.label_xmin_title.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_xmin_title.setVisible(False)
        self.label_xmin_title.setText("X最小值:")
        self.label_xmin_title.setObjectName("label_xmin_title")
        
        self.label_ymin_title = QtWidgets.QLabel(self.centralwidget)
        self.label_ymin_title.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_ymin_title.setVisible(False)
        self.label_ymin_title.setText("Y最小值:")
        self.label_ymin_title.setObjectName("label_ymin_title")
        
        self.label_xmax_title = QtWidgets.QLabel(self.centralwidget)
        self.label_xmax_title.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_xmax_title.setVisible(False)
        self.label_xmax_title.setText("X最大值:")
        self.label_xmax_title.setObjectName("label_xmax_title")
        
        self.label_ymax_title = QtWidgets.QLabel(self.centralwidget)
        self.label_ymax_title.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_ymax_title.setVisible(False)
        self.label_ymax_title.setText("Y最大值:")
        self.label_ymax_title.setObjectName("label_ymax_title")
        
        # 隐藏的第二手势坐标（保持兼容性）
        self.label_xmin_result_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_xmin_result_2.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_xmin_result_2.setVisible(False)
        self.label_xmin_result_2.setText("0")
        self.label_xmin_result_2.setObjectName("label_xmin_result_2")
        
        self.label_ymin_result_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ymin_result_2.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_ymin_result_2.setVisible(False)
        self.label_ymin_result_2.setText("0")
        self.label_ymin_result_2.setObjectName("label_ymin_result_2")
        
        self.label_xmax_result_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_xmax_result_2.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_xmax_result_2.setVisible(False)
        self.label_xmax_result_2.setText("0")
        self.label_xmax_result_2.setObjectName("label_xmax_result_2")
        
        self.label_ymax_result_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ymax_result_2.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_ymax_result_2.setVisible(False)
        self.label_ymax_result_2.setText("0")
        self.label_ymax_result_2.setObjectName("label_ymax_result_2")
        
        # 设置中心部件
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智能手势识别系统"))
        self.label_title.setText(_translate("MainWindow", "智能手势识别系统"))
        self.label_display.setText(_translate("MainWindow", ""))
        self.label_operation_title.setText(_translate("MainWindow", "操作区域"))
        self.toolButton_pic.setText(_translate("MainWindow", "图片"))
        self.textEdit_pic.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">请选择图片文件</p></body></html>"))
        self.toolButton_camera.setText(_translate("MainWindow", "摄像头"))
        self.textEdit_camera.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">实时摄像未开启</p></body></html>"))
        self.toolButton_video.setText(_translate("MainWindow", "视频"))
        self.textEdit_video.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">请选择视频文件</p></body></html>"))
        self.label_status_title.setText(_translate("MainWindow", "状态信息"))
        self.label_fps_title.setText(_translate("MainWindow", "FPS:"))
        self.label_time_result.setText(_translate("MainWindow", "0"))
        self.label_gesture_num.setText(_translate("MainWindow", "手势数目:"))
        self.label_numer_result.setText(_translate("MainWindow", "0"))
        self.result_title.setText(_translate("MainWindow", "手势 1"))
        self.label_result.setText(_translate("MainWindow", "结果:"))
        self.label_class_result.setText(_translate("MainWindow", "None"))
        
        # 恢复手指数标签
        self.label_finger_num.setText(_translate("MainWindow", "手指数:"))
        self.label_numer_score.setText(_translate("MainWindow", "0"))
        
        self.result2_title.setText(_translate("MainWindow", "手势 2"))
        self.label_result2.setText(_translate("MainWindow", "结果:"))
        self.label_class_result_2.setText(_translate("MainWindow", "None"))
        
        # 恢复第二个手指数标签
        self.label_finger_num_2.setText(_translate("MainWindow", "手指数:"))
        self.label_numer_score_2.setText(_translate("MainWindow", "0"))
        
        self.label_coordinates_title.setText(_translate("MainWindow", "坐标信息"))
        self.label_xmin_title.setText(_translate("MainWindow", "X最小值:"))
        self.label_xmin_result.setText(_translate("MainWindow", "0"))
        self.label_ymin_title.setText(_translate("MainWindow", "Y最小值:"))
        self.label_ymin_result.setText(_translate("MainWindow", "0"))
        self.label_xmax_title.setText(_translate("MainWindow", "X最大值:"))
        self.label_xmax_result.setText(_translate("MainWindow", "0"))
        self.label_ymax_title.setText(_translate("MainWindow", "Y最大值:"))
        self.label_ymax_result.setText(_translate("MainWindow", "0"))
        
        # 设置阈值滑块标签
        self.label_conf_threshold.setText(_translate("MainWindow", "置信度阈值:"))
        self.label_conf_value.setText(_translate("MainWindow", "0.5"))
        self.label_iou_threshold.setText(_translate("MainWindow", "IOU阈值:"))
        self.label_iou_value.setText(_translate("MainWindow", "0.5"))
        
        # 下拉框默认值
        self.comboBox_select.setItemText(0, _translate("MainWindow", "所有手势"))
        
        # 设置阈值滑块标签 - 手势1
        self.label_conf_threshold_1.setText(_translate("MainWindow", "置信度:"))
        self.label_conf_value_1.setText(_translate("MainWindow", "0.5"))
        self.label_iou_threshold_1.setText(_translate("MainWindow", "IOU:"))
        self.label_iou_value_1.setText(_translate("MainWindow", "0.5"))
        
        # 设置阈值滑块标签 - 手势2
        self.label_conf_threshold_2.setText(_translate("MainWindow", "置信度:"))
        self.label_conf_value_2.setText(_translate("MainWindow", "0.5"))
        self.label_iou_threshold_2.setText(_translate("MainWindow", "IOU:"))
        self.label_iou_value_2.setText(_translate("MainWindow", "0.5"))
        self.label_result_title.setText(_translate("MainWindow", "识别结果"))
